global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'debezium-ai'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['debezium-ai:8080']
        labels:
          application: 'debezium-ai'

  - job_name: 'debezium-connect'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['debezium-connect:8083']
        labels:
          application: 'debezium-connect'
