package io.debezium.pipeline.generator.service;

import io.debezium.pipeline.generator.model.*;
import io.quarkus.logging.Log;
import jakarta.enterprise.context.ApplicationScoped;

import java.util.*;
import java.util.stream.Collectors;

@ApplicationScoped
public class DeploymentGenerator {

    public record DeploymentArtifacts(
        String dockerCompose,
        String kubernetesYaml,
        String helmValues,
        String strimziKafkaConnector,
        String terraform,
        Map<String, String> additionalFiles
    ) {}

    public DeploymentArtifacts generate(PipelineSpec spec) {
        Map<String, String> additional = new HashMap<>();
        
        String dockerCompose = generateDockerCompose(spec);
        String kubernetesYaml = generateKubernetes(spec);
        String helmValues = generateHelmValues(spec);
        String strimziConnector = generateStrimziConnector(spec);
        String terraform = generateTerraform(spec);

        additional.put("README.md", generateReadme(spec));
        additional.put("deploy.sh", generateDeployScript(spec));
        additional.put(".env.example", generateEnvExample(spec));

        return new DeploymentArtifacts(
            dockerCompose,
            kubernetesYaml,
            helmValues,
            strimziConnector,
            terraform,
            additional
        );
    }

    private String generateDockerCompose(PipelineSpec spec) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Docker Compose for Debezium Pipeline\n");
        sb.append("# Generated by Debezium Pipeline Generator\n");
        sb.append("version: '3.8'\n\n");
        
        sb.append("services:\n");
        sb.append("  zookeeper:\n");
        sb.append("    image: confluentinc/cp-zookeeper:7.5.0\n");
        sb.append("    environment:\n");
        sb.append("      ZOOKEEPER_CLIENT_PORT: 2181\n");
        sb.append("      ZOOKEEPER_TICK_TIME: 2000\n\n");
        
        sb.append("  kafka:\n");
        sb.append("    image: confluentinc/cp-kafka:7.5.0\n");
        sb.append("    depends_on:\n");
        sb.append("      - zookeeper\n");
        sb.append("    ports:\n");
        sb.append("      - \"9092:9092\"\n");
        sb.append("    environment:\n");
        sb.append("      KAFKA_BROKER_ID: 1\n");
        sb.append("      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181\n");
        sb.append("      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092\n");
        sb.append("      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1\n\n");
        
        sb.append("  schema-registry:\n");
        sb.append("    image: confluentinc/cp-schema-registry:7.5.0\n");
        sb.append("    depends_on:\n");
        sb.append("      - kafka\n");
        sb.append("    ports:\n");
        sb.append("      - \"8081:8081\"\n");
        sb.append("    environment:\n");
        sb.append("      SCHEMA_REGISTRY_HOST_NAME: schema-registry\n");
        sb.append("      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092\n\n");
        
        sb.append("  connect:\n");
        sb.append("    image: debezium/connect:3.7\n");
        sb.append("    depends_on:\n");
        sb.append("      - kafka\n");
        sb.append("      - schema-registry\n");
        sb.append("    ports:\n");
        sb.append("      - \"8083:8083\"\n");
        sb.append("    environment:\n");
        sb.append("      BOOTSTRAP_SERVERS: kafka:9092\n");
        sb.append("      GROUP_ID: debezium-connect\n");
        sb.append("      CONFIG_STORAGE_TOPIC: debezium-config\n");
        sb.append("      OFFSET_STORAGE_TOPIC: debezium-offsets\n");
        sb.append("      STATUS_STORAGE_TOPIC: debezium-status\n");
        sb.append("      KEY_CONVERTER: io.apicurio.registry.utils.serde.AvroConverter\n");
        sb.append("      VALUE_CONVERTER: io.apicurio.registry.utils.serde.AvroConverter\n");
        sb.append("      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081\n");
        sb.append("      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081\n");
        
        if (spec.sourceConnector() != null && spec.sourceConnector().config() != null) {
            for (Map.Entry<String, String> entry : spec.sourceConnector().config().entrySet()) {
                if (entry.getKey().startsWith("database.") || entry.getKey().startsWith("mongodb.")) {
                    String envKey = entry.getKey().toUpperCase().replace(".", "_");
                    sb.append("      ").append(envKey).append(": \"").append(entry.getValue()).append("\"\n");
                }
            }
        }
        
        sb.append("\n  # Source database (add your database here)\n");
        sb.append("  # source-db:\n");
        sb.append("  #   image: ...\n");
        
        return sb.toString();
    }

    private String generateKubernetes(PipelineSpec spec) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Kubernetes Deployment for Debezium Pipeline\n");
        sb.append("# Generated by Debezium Pipeline Generator\n");
        sb.append("apiVersion: v1\n");
        sb.append("kind: Namespace\n");
        sb.append("metadata:\n");
        sb.append("  name: ").append(spec.deployment().namespace()).append("\n");
        sb.append("---\n");
        
        // Kafka Connect Deployment
        sb.append("apiVersion: apps/v1\n");
        sb.append("kind: Deployment\n");
        sb.append("metadata:\n");
        sb.append("  name: debezium-connect\n");
        sb.append("  namespace: ").append(spec.deployment().namespace()).append("\n");
        sb.append("spec:\n");
        sb.append("  replicas: ").append(spec.deployment().replicas()).append("\n");
        sb.append("  selector:\n");
        sb.append("    matchLabels:\n");
        sb.append("      app: debezium-connect\n");
        sb.append("  template:\n");
        sb.append("    metadata:\n");
        sb.append("      labels:\n");
        sb.append("        app: debezium-connect\n");
        if (spec.deployment().labels() != null) {
            for (Map.Entry<String, String> label : spec.deployment().labels().entrySet()) {
                sb.append("        ").append(label.getKey()).append(": ").append(label.getValue()).append("\n");
            }
        }
        sb.append("    spec:\n");
        sb.append("      containers:\n");
        sb.append("      - name: connect\n");
        sb.append("        image: debezium/connect:3.7\n");
        sb.append("        ports:\n");
        sb.append("        - containerPort: 8083\n");
        sb.append("        env:\n");
        sb.append("        - name: BOOTSTRAP_SERVERS\n");
        sb.append("          value: \"").append(spec.sourceConnector().kafka().bootstrapServers()).append("\"\n");
        sb.append("        - name: GROUP_ID\n");
        sb.append("          value: \"debezium-connect\"\n");
        sb.append("        - name: CONFIG_STORAGE_TOPIC\n");
        sb.append("          value: \"debezium-config\"\n");
        sb.append("        - name: OFFSET_STORAGE_TOPIC\n");
        sb.append("          value: \"debezium-offsets\"\n");
        sb.append("        - name: STATUS_STORAGE_TOPIC\n");
        sb.append("          value: \"debezium-status\"\n");
        sb.append("        - name: KEY_CONVERTER\n");
        sb.append("          value: \"io.apicurio.registry.utils.serde.AvroConverter\"\n");
        sb.append("        - name: VALUE_CONVERTER\n");
        sb.append("          value: \"io.apicurio.registry.utils.serde.AvroConverter\"\n");
        sb.append("        - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL\n");
        sb.append("          value: \"").append(spec.schemaRegistry().url()).append("\"\n");
        sb.append("        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL\n");
        sb.append("          value: \"").append(spec.schemaRegistry().url()).append("\"\n");
        
        if (spec.deployment().resources() != null) {
            sb.append("        resources:\n");
            ResourceRequirements res = spec.deployment().resources();
            if (res.cpuRequest() != null) {
                sb.append("          requests:\n");
                sb.append("            cpu: \"").append(res.cpuRequest()).append("\"\n");
            }
            if (res.memoryRequest() != null) {
                sb.append("            memory: \"").append(res.memoryRequest()).append("\"\n");
            }
            if (res.cpuLimit() != null) {
                sb.append("          limits:\n");
                sb.append("            cpu: \"").append(res.cpuLimit()).append("\"\n");
            }
            if (res.memoryLimit() != null) {
                sb.append("            memory: \"").append(res.memoryLimit()).append("\"\n");
            }
        }
        
        sb.append("---\n");
        sb.append("apiVersion: v1\n");
        sb.append("kind: Service\n");
        sb.append("metadata:\n");
        sb.append("  name: debezium-connect\n");
        sb.append("  namespace: ").append(spec.deployment().namespace()).append("\n");
        sb.append("spec:\n");
        sb.append("  ports:\n");
        sb.append("  - port: 8083\n");
        sb.append("    targetPort: 8083\n");
        sb.append("  selector:\n");
        sb.append("    app: debezium-connect\n");
        
        return sb.toString();
    }

    private String generateHelmValues(PipelineSpec spec) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Helm values for Strimzi Kafka and Debezium Connect\n");
        sb.append("# Generated by Debezium Pipeline Generator\n\n");
        
        sb.append("strimzi:\n");
        sb.append("  version: ").append(spec.deployment().strimziVersion()).append("\n\n");
        
        sb.append("kafka:\n");
        sb.append("  replicas: 3\n");
        sb.append("  resources:\n");
        sb.append("    requests:\n");
        sb.append("      memory: 1Gi\n");
        sb.append("      cpu: 500m\n");
        sb.append("    limits:\n");
        sb.append("      memory: 2Gi\n");
        sb.append("      cpu: 1000m\n\n");
        
        sb.append("zookeeper:\n");
        sb.append("  replicas: 3\n\n");
        
        sb.append("connect:\n");
        sb.append("  replicas: ").append(spec.deployment().replicas()).append("\n");
        sb.append("  image: debezium/connect:3.7\n");
        sb.append("  bootstrapServers: ").append(spec.sourceConnector().kafka().bootstrapServers()).append("\n");
        sb.append("  config:\n");
        sb.append("    group.id: debezium-connect\n");
        sb.append("    config.storage.topic: debezium-config\n");
        sb.append("    offset.storage.topic: debezium-offsets\n");
        sb.append("    status.storage.topic: debezium-status\n");
        sb.append("    key.converter: io.apicurio.registry.utils.serde.AvroConverter\n");
        sb.append("    value.converter: io.apicurio.registry.utils.serde.AvroConverter\n");
        sb.append("    key.converter.schema.registry.url: ").append(spec.schemaRegistry().url()).append("\n");
        sb.append("    value.converter.schema.registry.url: ").append(spec.schemaRegistry().url()).append("\n");
        
        if (spec.deployment().resources() != null) {
            sb.append("  resources:\n");
            ResourceRequirements res = spec.deployment().resources();
            if (res.cpuRequest() != null) {
                sb.append("    requests:\n");
                sb.append("      cpu: \"").append(res.cpuRequest()).append("\"\n");
            }
            if (res.memoryRequest() != null) {
                sb.append("      memory: \"").append(res.memoryRequest()).append("\"\n");
            }
            if (res.cpuLimit() != null) {
                sb.append("    limits:\n");
                sb.append("      cpu: \"").append(res.cpuLimit()).append("\"\n");
            }
            if (res.memoryLimit() != null) {
                sb.append("      memory: \"").append(res.memoryLimit()).append("\"\n");
            }
        }
        
        return sb.toString();
    }

    private String generateStrimziConnector(PipelineSpec spec) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Strimzi KafkaConnector Custom Resource\n");
        sb.append("# Generated by Debezium Pipeline Generator\n");
        sb.append("apiVersion: kafka.strimzi.io/v1beta2\n");
        sb.append("kind: KafkaConnector\n");
        sb.append("metadata:\n");
        sb.append("  name: ").append(spec.sourceConnector().name()).append("\n");
        sb.append("  labels:\n");
        sb.append("    strimzi.io/cluster: ").append(spec.deployment().connectClusterName()).append("\n");
        sb.append("spec:\n");
        sb.append("  class: ").append(spec.sourceConnector().connectorClass()).append("\n");
        sb.append("  tasksMax: 1\n");
        sb.append("  config:\n");
        
        if (spec.sourceConnector().config() != null) {
            for (Map.Entry<String, String> entry : spec.sourceConnector().config().entrySet()) {
                sb.append("    ").append(entry.getKey()).append(": \"").append(entry.getValue()).append("\"\n");
            }
        }
        
        if (spec.sourceConnector().transforms() != null) {
            int i = 0;
            for (TransformConfig transform : spec.sourceConnector().transforms()) {
                sb.append("    transforms: \"").append(transform.name()).append("\"\n");
                sb.append("    transforms.").append(transform.name()).append(".type: ").append(transform.type()).append("\n");
                if (transform.config() != null) {
                    for (Map.Entry<String, String> entry : transform.config().entrySet()) {
                        sb.append("    transforms.").append(transform.name()).append(".").append(entry.getKey()).append(": \"").append(entry.getValue()).append("\"\n");
                    }
                }
                if (transform.predicate() != null) {
                    sb.append("    transforms.").append(transform.name()).append(".predicate: \"").append(transform.predicate()).append("\"\n");
                }
                i++;
            }
        }
        
        if (spec.sourceConnector().predicates() != null) {
            for (Map.Entry<String, String> entry : spec.sourceConnector().predicates().entrySet()) {
                sb.append("    predicates.").append(entry.getKey()).append(": \"").append(entry.getValue()).append("\"\n");
            }
        }
        
        return sb.toString();
    }

    private String generateTerraform(PipelineSpec spec) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Terraform configuration for Debezium Pipeline\n");
        sb.append("# Generated by Debezium Pipeline Generator\n\n");
        
        sb.append("terraform {\n");
        sb.append("  required_version = \">= 1.0\"\n");
        sb.append("  required_providers {\n");
        sb.append("    kubernetes = {\n");
        sb.append("      source  = \"hashicorp/kubernetes\"\n");
        sb.append("      version = \"~> 2.23\"\n");
        sb.append("    }\n");
        sb.append("    helm = {\n");
        sb.append("      source  = \"hashicorp/helm\"\n");
        sb.append("      version = \"~> 2.10\"\n");
        sb.append("    }\n");
        sb.append("  }\n");
        sb.append("}\n\n");
        
        sb.append("provider \"kubernetes\" {\n");
        sb.append("  config_path = \"~/.kube/config\"\n");
        sb.append("}\n\n");
        
        sb.append("provider \"helm\" {\n");
        sb.append("  kubernetes {\n");
        sb.append("    config_path = \"~/.kube/config\"\n");
        sb.append("  }\n");
        sb.append("}\n\n");
        
        sb.append("resource \"kubernetes_namespace\" \"debezium\" {\n");
        sb.append("  metadata {\n");
        sb.append("    name = \"").append(spec.deployment().namespace()).append("\"\n");
        sb.append("  }\n");
        sb.append("}\n\n");
        
        sb.append("resource \"helm_release\" \"strimzi_kafka\" {\n");
        sb.append("  name       = \"strimzi-kafka\"\n");
        sb.append("  repository = \"https://strimzi.io/charts/\"\n");
        sb.append("  chart      = \"strimzi-kafka-operator\"\n");
        sb.append("  version    = \"").append(spec.deployment().strimziVersion()).append("\"\n");
        sb.append("  namespace  = kubernetes_namespace.debezium.metadata[0].name\n");
        sb.append("}\n\n");
        
        sb.append("resource \"helm_release\" \"debezium_connect\" {\n");
        sb.append("  name       = \"debezium-connect\"\n");
        sb.append("  repository = \"https://debezium.io/charts/\"\n");
        sb.append("  chart      = \"debezium-connect\"\n");
        sb.append("  namespace  = kubernetes_namespace.debezium.metadata[0].name\n");
        sb.append("  depends_on = [helm_release.strimzi_kafka]\n");
        sb.append("  set {\n");
        sb.append("    name  = \"connect.bootstrapServers\"\n");
        sb.append("    value = \"").append(spec.sourceConnector().kafka().bootstrapServers()).append("\"\n");
        sb.append("  }\n");
        sb.append("  set {\n");
        sb.append("    name  = \"connect.schemaRegistryUrl\"\n");
        sb.append("    value = \"").append(spec.schemaRegistry().url()).append("\"\n");
        sb.append("  }\n");
        sb.append("}\n");
        
        return sb.toString();
    }

    private String generateReadme(PipelineSpec spec) {
        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(spec.name()).append("\n\n");
        sb.append(spec.description()).append("\n\n");
        sb.append("## Overview\n\n");
        sb.append("This pipeline captures changes from **").append(spec.sourceConnector().type()).append("** ");
        sb.append("and delivers them to **").append(spec.sinkConnector() != null ? spec.sinkConnector().type() : "Kafka topics").append("**.\n\n");
        
        sb.append("## Quick Start\n\n");
        sb.append("### Docker Compose\n");
        sb.append("```bash\n");
        sb.append("docker-compose up -d\n");
        sb.append("```\n\n");
        
        sb.append("### Kubernetes (Strimzi)\n");
        sb.append("```bash\n");
        sb.append("kubectl apply -f kubernetes/\n");
        sb.append("```\n\n");
        
        sb.append("### Helm\n");
        sb.append("```bash\n");
        sb.append("helm install debezium ./helm -f values.yaml\n");
        sb.append("```\n\n");
        
        sb.append("### Terraform\n");
        sb.append("```bash\n");
        sb.append("terraform init\n");
        sb.append("terraform apply\n");
        sb.append("```\n\n");
        
        sb.append("## Configuration\n\n");
        sb.append("### Source Connector\n");
        sb.append("```json\n");
        sb.append(toJson(spec.sourceConnector().config())).append("\n");
        sb.append("```\n\n");
        
        if (spec.sinkConnector() != null) {
            sb.append("### Sink Connector\n");
            sb.append("```json\n");
            sb.append(toJson(spec.sinkConnector().config())).append("\n");
            sb.append("```\n\n");
        }
        
        sb.append("## Topics\n\n");
        if (spec.mappings() != null) {
            for (MappingRule mapping : spec.mappings()) {
                sb.append("- `").append(mapping.sourceTopic()).append("` -> `").append(mapping.targetTopic()).append("`\n");
            }
        }
        
        sb.append("\n## Monitoring\n\n");
        sb.append("- Kafka Connect REST API: `http://localhost:8083`\n");
        sb.append("- Schema Registry: `http://localhost:8081`\n");
        sb.append("- Prometheus metrics: `http://localhost:9404/metrics`\n");
        
        return sb.toString();
    }

    private String generateDeployScript(PipelineSpec spec) {
        StringBuilder sb = new StringBuilder();
        sb.append("#!/bin/bash\n");
        sb.append("# Deploy script for ").append(spec.name()).append("\n");
        sb.append("# Generated by Debezium Pipeline Generator\n\n");
        
        sb.append("set -e\n\n");
        
        sb.append("DEPLOYMENT_TYPE=\"${1:-docker-compose}\"\n\n");
        
        sb.append("case $DEPLOYMENT_TYPE in\n");
        sb.append("  docker-compose)\n");
        sb.append("    docker-compose up -d\n");
        sb.append("    ;;\n");
        sb.append("  kubernetes)\n");
        sb.append("    kubectl apply -f kubernetes/\n");
        sb.append("    ;;\n");
        sb.append("  helm)\n");
        sb.append("    helm install debezium ./helm -f values.yaml\n");
        sb.append("    ;;\n");
        sb.append("  terraform)\n");
        sb.append("    terraform init && terraform apply\n");
        sb.append("    ;;\n");
        sb.append("  *)\n");
        sb.append("    echo \"Unknown deployment type: $DEPLOYMENT_TYPE\"\n");
        sb.append("    echo \"Usage: $0 [docker-compose|kubernetes|helm|terraform]\"\n");
        sb.append("    exit 1\n");
        sb.append("    ;;\n");
        sb.append("esac\n\n");
        
        sb.append("echo \"Deployment complete!\"\n");
        sb.append("echo \"Kafka Connect: http://localhost:8083\"\n");
        sb.append("echo \"Schema Registry: http://localhost:8081\"\n");
        
        return sb.toString();
    }

    private String generateEnvExample(PipelineSpec spec) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Environment variables for ").append(spec.name()).append("\n");
        sb.append("# Copy to .env and fill in values\n\n");
        
        if (spec.sourceConnector().config() != null) {
            for (Map.Entry<String, String> entry : spec.sourceConnector().config().entrySet()) {
                if (entry.getKey().contains("password") || entry.getKey().contains("secret") || entry.getKey().contains("key")) {
                    String envKey = entry.getKey().toUpperCase().replace(".", "_");
                    sb.append(envKey).append("=your-secret-here\n");
                }
            }
        }
        
        sb.append("\nKAFKA_BOOTSTRAP_SERVERS=localhost:9092\n");
        sb.append("SCHEMA_REGISTRY_URL=http://localhost:8081\n");
        
        return sb.toString();
    }

    private String toJson(Map<String, String> map) {
        if (map == null || map.isEmpty()) return "{}";
        StringBuilder sb = new StringBuilder();
        sb.append("{\n");
        int i = 0;
        for (Map.Entry<String, String> entry : map.entrySet()) {
            sb.append("  \"").append(entry.getKey()).append("\": \"").append(entry.getValue()).append("\"");
            if (i < map.size() - 1) sb.append(",");
            sb.append("\n");
            i++;
        }
        sb.append("}");
        return sb.toString();
    }
}