package io.debezium.v4.api.auth;

public enum Permission {
    PIPELINE_CREATE,   PIPELINE_READ,   PIPELINE_UPDATE,   PIPELINE_DELETE,
    PIPELINE_DEPLOY,   PIPELINE_START,  PIPELINE_STOP,
    CONNECTOR_CREATE,  CONNECTOR_READ,  CONNECTOR_UPDATE,  CONNECTOR_DELETE,
    MAPPING_CREATE,    MAPPING_READ,    MAPPING_UPDATE,    MAPPING_DELETE,
    METRICS_READ,      METRICS_WRITE,
    AUDIT_READ,
    USER_CREATE,       USER_READ,       USER_UPDATE,       USER_DELETE,
    TENANT_CREATE,     TENANT_READ,     TENANT_UPDATE,     TENANT_DELETE,
    EXPORT,            IMPORT,
    DEPLOYMENT_READ,   DEPLOYMENT_CREATE, DEPLOYMENT_DELETE,
    SETTINGS_READ,     SETTINGS_WRITE,
    ALL
}
